# Write your MySQL query statement below
SELECT
    M.EMPLOYEE_ID,
    M.NAME,
    COUNT(E.EMPLOYEE_ID) AS REPORTS_COUNT,
    ROUND(AVG(E.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES  M
JOIN EMPLOYEES  E
ON M.EMPLOYEE_ID = E.REPORTS_TO
GROUP BY
    M.EMPLOYEE_ID,
    M.NAME
ORDER BY
    M.EMPLOYEE_ID;