# Write your MySQL query statement below
SELECT DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH,
COUNTRY,COUNT(*) AS TRANS_COUNT,
SUM(STATE = 'APPROVED') AS APPROVED_COUNT,
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(CASE WHEN STATE = 'APPROVED' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY DATE_FORMAT(TRANS_DATE, '%Y-%m'),COUNTRY;